name: Name of Workflow
on: workflow_dispatch # make sure that we can manually trigger this Workflow
jobs: # Has to be jobS
  first-job: # Name of the job
    runs-on: ubuntu-latest
    steps: 
      - name: Print green
        run:  echo "Hello world"
      - name: Print good bye
        run:  echo "Done - bye!"